USE master;
ALTER AUTHORIZATION ON DATABASE::CASTILLONV2 TO SA;

USE CASTILLONV2

SELECT 
E.IDEMPLEADO AS 'ID_EMPLEADO'
, DEP.NOMDEPARTAMENTO AS DEPARTAMENTO
, PRO.NOMPROVINCIA AS PROVINCIA
, DIS.NOMDISTRITO AS DISTRITO
,(P.NOMBRES+' '+P.APEPATERNO+' '+P.APEMATERNO) AS EMPLEADO
,E.SALARIO
, CASE WHEN E.SALARIO < 1000 THEN 'BONO DE 30%' ELSE 'BONO 5%' END AS BONO
, CASE 
	WHEN E.SALARIO < 1000 
	THEN FORMAT(((E.SALARIO/100)*30)+E.SALARIO,'###,##0') 
	ELSE FORMAT(((E.SALARIO/100)*5)+E.SALARIO,'###,##0')
   END AS 'SUELDO TOTAL'
FROM EMPLEADO E

INNER JOIN PERSONA P
ON E.IDEMPLEADO = P.IDPERSONA 
INNER JOIN DEPARTAMENTO DEP
ON E.IDEMPLEADO = DEP.IDDepartamento
INNER JOIN PROVINCIA PRO
ON E.IDEMPLEADO = PRO.IDPROVINCIA
INNER JOIN DISTRITO DIS
ON E.IDEMPLEADO = DIS.IDDISTRITO

ORDER BY BONO ASC;

